[package]
name = "auditorium"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.45"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ffprobe = "0.4.0"
random-number = "0.1.9"
ratatui = "0.29.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.143"
textwrap = "0.16.2"
