[package]
name = "auditorium"
version = "1.0.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
ffprobe = "0.4.0"
random-number = "0.1.9"
ratatui = { version = "0.29.0", features = ["serde"] }
rayon = "1.11.0"
rlimit = "0.10.2"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.143"
textwrap = "0.16.2"
